openapi: 3.0.0
info:
  title: Portfolio Management API
  version: 1.0.0
  description: API for managing accounts, transactions, and currencies

tags:
  - name: Accounts
    description: Operations related to accounts
  - name: Transactions
    description: Operations related to transactions
  - name: Currencies
    description: Operations related to currencies

components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: integer
        user_name:
          type: string
        currency_name:
          type: string
        transaction_RIB:
          type: string
        wallet:
          type: integer
    
    Currency:
      type: object
      properties:
        name:
          type: string

paths:
  /accounts:
    get:
      summary: Get all accounts
      tags:
        - Accounts
      responses:
        '200':
          description: List of all accounts
    
    put:
      summary: Add a new account
      tags:
        - Accounts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        '201':
          description: New account added

  /transactions:
    get:
      summary: Get all transactions
      tags:
        - Transactions
      responses:
        '200':
          description: List of all transactions

  /currencies:
    get:
      summary: Get all currencies
      tags:
        - Currencies
      responses:
        '200':
          description: List of all currencies
    
    put:
      summary: Add a new currency
      tags:
        - Currencies
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Currency'
      responses:
        '201':
          description: New currency added
